//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xphter.Framework.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xphter.Framework.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow {
            get {
                object obj = ResourceManager.GetObject("Arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2011-05-04
        ///开启或禁用远程桌面的方法：
        ///1. 注册表：设置 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\fDenyTSConnections 的值；
        ///2. 组策略：配置 计算机配置 -&gt; 管理模板 -&gt; Windows 组建 -&gt; 终端服务 -&gt; 允许用户使用终端服务进行远程连接 的值；
        ///
        ///修改远程桌面端口号的方法：
        ///设置 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\Wds\rdpwd\Tds\tcp\PortNumber 的值；
        ///设置 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\PortNumber 的值；
        ///在Windows防火墙中增加例外规则，尚不清楚如何修改Windows防火墙中默认远程桌面的规则；
        ///
        ///2011-05-06
        ///在客户端javascript代码中安全 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AsyncFileStream {
            get {
                return ResourceManager.GetString("AsyncFileStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Car {
            get {
                object obj = ResourceManager.GetObject("Car", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CityWeekly {
            get {
                object obj = ResourceManager.GetObject("CityWeekly", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Deramon {
            get {
                object obj = ResourceManager.GetObject("Deramon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document.writeln(&quot;&lt;div style=\&quot;width: 100%; height: [x:AdvertisementProperty Property=&apos;图片高度&apos; /]; background: transparent url(\&apos;[x:AdvertisementProperty Property=`图片文件` /]\&apos;) scroll no-repeat center top;\&quot;&gt;&quot;);
        ///document.writeln(&quot;    &lt;a href=\&quot;[x:AdvertisementLink Ordinal=&apos;0&apos; /]\&quot; target=\&quot;[x:AdvertisementProperty Property=&apos;目标窗口&apos; /]\&quot; style=\&quot;display: block; width: 100%; height: 100%;\&quot;&gt;&lt;/a&gt;&quot;);
        ///document.writeln(&quot;&lt;/div&gt;&quot;);.
        /// </summary>
        internal static string HtmlAnalyzer_OnlyJavaScript {
            get {
                return ResourceManager.GetString("HtmlAnalyzer_OnlyJavaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///	&lt;object type=&quot;Test.IClassA&quot; class=&quot;Test.ClassA1&quot; /&gt;
        ///	&lt;object type=&quot;Test.ClassA1&quot;&gt;
        ///        &lt;argument type=&quot;System.Bool&quot; value=&quot;True&quot; /&gt;
        ///        &lt;argument type=&quot;System.Char&quot; /&gt;
        ///		&lt;argument type=&quot;System.String&quot; value=&quot;嘿嘿哈嘿&quot; /&gt;
        ///		&lt;argument type=&quot;System.Int32&quot; value=&quot;13&quot; /&gt;
        ///		&lt;argument type=&quot;System.Float&quot; /&gt;
        ///		&lt;argument type=&quot;System.Double&quot; /&gt;
        ///		&lt;argument type=&quot;System.Decimal&quot; value=&quot;13.13&quot; /&gt;
        ///        &lt;argument type=&quot;System.DateTime&quot; value=&quot;2011- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ObjectFactory {
            get {
                return ResourceManager.GetString("ObjectFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xml&gt;
        ///&lt;ToUserName&gt;&lt;![CDATA[toUser]]&gt;&lt;/ToUserName&gt;
        ///&lt;FromUserName&gt;&lt;![CDATA[fromUser]]&gt;&lt;/FromUserName&gt; 
        ///&lt;CreateTime&gt;1348831860&lt;/CreateTime&gt;
        ///&lt;MsgType&gt;&lt;![CDATA[text]]&gt;&lt;/MsgType&gt;
        ///&lt;Content&gt;&lt;![CDATA[this is a test]]&gt;&lt;/Content&gt;
        ///&lt;MsgId&gt;1234567890123456&lt;/MsgId&gt;
        ///&lt;/xml&gt;.
        /// </summary>
        internal static string WeChatTextMessage {
            get {
                return ResourceManager.GetString("WeChatTextMessage", resourceCulture);
            }
        }
    }
}
